name: hello-world

on: repository_dispatch

jobs:
  hello-world-job:
    runs-on: ubuntu-latest

    steps:
      - name: check out repository code
        uses: actions/checkout@v2
      - run: echo "$(cat hello_world.txt)"
